### ISSUE TITLE
[Question]: How to add health checks and circuit breaker rules in Easegress K8S Ingress configuration?

### ISSUE THREAD

**Issue by tjqc0512** [easegress-io/easegress#1361]
### This is not Bug report or Feature request

- [X] I confirm that this is not bug report or feature request.

### Is this question answered in [the documentation](https://github.com/megaease/easegress/blob/main/doc/README.md)?

- [X] I have searched the documentation

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Your question

Hello,
I am using Easegress as an Ingress Controller in K8S, but I cannot find a way to add health checks or circuit breaker rules in the Ingress YAML configuration file. I have checked the documentation and the code in /pkg/object/ingresscontroller, but I couldn't find any related code that converts Ingress configurations into proxy health checks or circuit breaker rules.
Could you please provide any examples or guidance to help me implement these features in the Ingress configuration?
Thank you!
![image](https://github.com/user-attachments/assets/0cd8a14a-a328-4ac8-8f61-3f5267d1f73c)
![image](https://github.com/user-attachments/assets/807ab3e8-fd5d-4eda-899f-6a0872863919)

**Comment by suchen-sci** [comment]
Hi, 
Thank you for using Easegress!

Unfortunately, this feature is not available at the moment. The Easegress Ingress Controller translates Kubernetes Ingress specifications into our `HTTPServer` and `Pipeline`. Since Kubernetes Ingress does not provide health checks and circuit breakers, we are unable to support them. 

However, you can try using [Kubernetes pod health checks](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) instead. Or even run a Easegress behind the k8s Ingress, then you can write `HTTPServer` and `Pipeline` as you like.

**Comment by tjqc0512** [comment]
@suchen-sci 
Thank you very much for your response! Through reading the documentation, I learned that Easegress supports RateLimiter and CircuitBreaker functionality as a Kubernetes Gateway API. We plan to use the Kubernetes Gateway API to replace Ingress to meet our health monitoring needs. I have two questions that I hope you can answer:
When using Easegress as a Kubernetes Gateway API, is it necessary to install any additional software, such as EaseMesh, to enable the RateLimiter and CircuitBreaker functionalities?
How well does Easegress support HTTP/3 traffic as a Kubernetes Gateway API?
